//! Staging `ext-workspace-v1` workspace enumeration and activation.
//!
//! Halley's cluster model stays authoritative. This module never stores a
//! second mutable workspace model: it translates a read-only [`Snapshot`] of
//! `ClusterSystem` into protocol objects, and reduces the requests a client
//! queues before `commit` into a single [`TransactionPlan`] that the session
//! applies through its existing activation helpers.
//!
//! Two things keep this module honest:
//!
//! * Protocol state is per manager *binding*, not per client. A client may bind
//!   `ext_workspace_manager_v1` more than once and must then see independent
//!   handles for the same workspaces.
//! * Nothing here depends on `crate::`, so `tests/ext_workspace_protocol.rs`
//!   includes this file directly with `#[path]` and drives the production
//!   dispatch code over a real Wayland socket without initializing DRM or EGL.
//!
//! Protocol reference: `protocols/staging/ext-workspace/ext-workspace-v1.xml`.

use std::collections::HashMap;

use smithay::output::Output;
use smithay::reexports::wayland_protocols::ext::workspace::v1::server::{
    ext_workspace_group_handle_v1::{self, ExtWorkspaceGroupHandleV1},
    ext_workspace_handle_v1::{self, ExtWorkspaceHandleV1},
    ext_workspace_manager_v1::{self, ExtWorkspaceManagerV1},
};
use smithay::reexports::wayland_server::backend::{ClientId, GlobalId, ObjectId};
use smithay::reexports::wayland_server::protocol::wl_output::WlOutput;
use smithay::reexports::wayland_server::{
    Client, DataInit, Dispatch, DisplayHandle, GlobalDispatch, New, Resource,
};

use halley_core::cluster::ClusterId;

/// The only protocol version Halley implements.
pub const VERSION: u32 = 1;

/// `ext_workspace_group_handle_v1.group_capabilities`: empty. Halley never
/// creates workspaces on a client's behalf, so `create_workspace` is advertised
/// as unavailable and ignored if it arrives anyway.
const GROUP_CAPABILITIES: ext_workspace_group_handle_v1::GroupCapabilities =
    ext_workspace_group_handle_v1::GroupCapabilities::from_bits_retain(0);

/// `ext_workspace_handle_v1.workspace_capabilities`: `activate | deactivate`.
/// Client-driven `remove` and `assign` stay unsupported.
const WORKSPACE_CAPABILITIES: ext_workspace_handle_v1::WorkspaceCapabilities =
    ext_workspace_handle_v1::WorkspaceCapabilities::from_bits_retain(
        ext_workspace_handle_v1::WorkspaceCapabilities::Activate.bits()
            | ext_workspace_handle_v1::WorkspaceCapabilities::Deactivate.bits(),
    );

// ---------------------------------------------------------------------------
// Model snapshot
// ---------------------------------------------------------------------------

/// A read-only view of everything the protocol can see.
///
/// Generated by the session from `ClusterSystem` at the event-loop boundary and
/// compared against each binding's last advertised values. There is no second
/// mutable workspace model here.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Snapshot {
    /// One group per currently mapped output, in output order.
    pub groups: Vec<GroupSnapshot>,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct GroupSnapshot {
    /// The mapped output this group belongs to.
    ///
    /// This is the output *identity*, not only its name: a monitor that
    /// disconnects and reconnects under the same name produces a different
    /// `Output`, so stale handles can never be revived accidentally.
    pub output: Output,
    /// Advertised clusters owned by this output, in slot order. Empty
    /// workspaces still appear; a cluster is omitted only while its output is
    /// not mapped.
    pub workspaces: Vec<WorkspaceSnapshot>,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct WorkspaceSnapshot {
    pub id: ClusterId,
    /// `ClusterMetadata::name`.
    pub name: String,
    /// Published slot, 1-based. Also the source of the protocol coordinate.
    pub order: u8,
    pub active: bool,
}

/// `ext_workspace_handle_v1.coordinates` carries one coordinate per dimension.
///
/// Halley orders clusters along a single dimension, so exactly one coordinate
/// is published: the 0-based published slot, in native endianness because
/// Wayland marshals integers in host byte order.
fn coordinates(order: u8) -> Vec<u8> {
    u32::from(order.saturating_sub(1)).to_ne_bytes().to_vec()
}

fn state_of(active: bool) -> ext_workspace_handle_v1::State {
    if active {
        ext_workspace_handle_v1::State::Active
    } else {
        ext_workspace_handle_v1::State::from_bits_retain(0)
    }
}

// ---------------------------------------------------------------------------
// Requests and transactions
// ---------------------------------------------------------------------------

/// The two workspace requests Halley advertises.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PendingAction {
    Activate,
    Deactivate,
}

/// One request queued since the last `commit`.
///
/// `remove`, `assign`, and `create_workspace` are ignored outright because
/// their capabilities are never advertised.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct PendingRequest {
    pub cluster: ClusterId,
    pub action: PendingAction,
    /// Object id of the handle the request arrived on.
    ///
    /// Carrying it lets `commit` discard a request sent on a handle that was
    /// since removed, even when the cluster itself is still advertised through
    /// a newer object.
    pub object: ObjectId,
}

/// The reduced result of one manager transaction.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct TransactionPlan {
    /// Final selection per output, in first-requested order, limited to outputs
    /// whose selection actually changes. `None` means "leave the output in
    /// Field mode".
    pub selections: Vec<(String, Option<ClusterId>)>,
    /// The single output and cluster that should take keyboard focus.
    ///
    /// A multi-output transaction still switches every changed output, but only
    /// one workspace may own the keyboard.
    pub focus: Option<(String, ClusterId)>,
}

impl TransactionPlan {
    pub fn is_empty(&self) -> bool {
        self.selections.is_empty()
    }
}

/// Reduces a transaction to the final state per output.
///
/// Requests are processed in order and the last request for an output wins.
/// `deactivate` clears a selection only when its target is the workspace that
/// would be active for that output, so deactivating an unrelated workspace
/// leaves the active selection alone. Targets are revalidated here rather than
/// trusted from queue time, which discards requests whose target disappeared
/// between the request and the commit.
pub fn reduce_transaction(
    requests: &[(ClusterId, PendingAction)],
    is_live: impl Fn(ClusterId) -> bool,
    owner_of: impl Fn(ClusterId) -> Option<String>,
    active_on: impl Fn(&str) -> Option<ClusterId>,
) -> TransactionPlan {
    let mut desired: Vec<(String, Option<ClusterId>)> = Vec::new();
    let mut last_activation: Option<(String, ClusterId)> = None;

    for (cluster, action) in requests {
        let cluster = *cluster;
        if !is_live(cluster) {
            continue;
        }
        let Some(output) = owner_of(cluster) else {
            continue;
        };
        match action {
            PendingAction::Activate => {
                set_desired(&mut desired, &output, Some(cluster));
                last_activation = Some((output, cluster));
            }
            PendingAction::Deactivate => {
                let current = desired
                    .iter()
                    .find(|(candidate, _)| *candidate == output)
                    .map(|(_, selection)| *selection)
                    .unwrap_or_else(|| active_on(&output));
                if current == Some(cluster) {
                    set_desired(&mut desired, &output, None);
                    if last_activation.as_ref() == Some(&(output.clone(), cluster)) {
                        last_activation = None;
                    }
                }
            }
        }
    }

    let selections = desired
        .into_iter()
        .filter(|(output, selection)| active_on(output) != *selection)
        .collect::<Vec<_>>();

    // Focus only the winning activation, and only when it really changed the
    // output's selection.
    let focus = last_activation.filter(|(output, cluster)| {
        selections
            .iter()
            .any(|(candidate, selection)| candidate == output && *selection == Some(*cluster))
    });

    TransactionPlan { selections, focus }
}

fn set_desired(
    desired: &mut Vec<(String, Option<ClusterId>)>,
    output: &str,
    value: Option<ClusterId>,
) {
    match desired
        .iter_mut()
        .find(|(candidate, _)| candidate == output)
    {
        Some(entry) => entry.1 = value,
        None => desired.push((output.to_string(), value)),
    }
}

// ---------------------------------------------------------------------------
// Protocol resources
// ---------------------------------------------------------------------------

/// Per-resource data for an advertised workspace group handle.
#[derive(Clone, Copy, Debug)]
pub struct GroupData {
    /// Identifies the manager binding that owns this handle.
    pub binding: u64,
}

/// Per-resource data for an advertised workspace handle.
#[derive(Clone, Copy, Debug)]
pub struct WorkspaceData {
    /// Identifies the manager binding that owns this handle.
    pub binding: u64,
    pub cluster: ClusterId,
}

struct GroupBinding {
    output: Output,
    handle: ExtWorkspaceGroupHandleV1,
    /// Set once the client destroyed the handle. The entry survives because it
    /// still records membership: a client that drops the group object keeps the
    /// workspace handles it already holds, and the dead object is never used
    /// again.
    detached: bool,
    /// `wl_output` resources already associated with this group, keyed by
    /// object id so a late bind can never double-send `output_enter`.
    outputs: HashMap<ObjectId, WlOutput>,
    /// Clusters currently advertised as members of this group.
    workspaces: Vec<ClusterId>,
}

struct WorkspaceBinding {
    cluster: ClusterId,
    handle: ExtWorkspaceHandleV1,
    /// Group this workspace is a member of, by output identity.
    group: Option<Output>,
    name: String,
    order: u8,
    active: bool,
    /// The client destroyed this handle: stop advertising the cluster to this
    /// binding instead of recreating the object on every synchronisation.
    detached: bool,
}

struct Binding {
    id: u64,
    client: Client,
    manager: ExtWorkspaceManagerV1,
    groups: Vec<GroupBinding>,
    workspaces: Vec<WorkspaceBinding>,
    pending: Vec<PendingRequest>,
}

/// All `ext-workspace-v1` protocol state.
pub struct State {
    _global: GlobalId,
    next_binding: u64,
    bindings: Vec<Binding>,
}

impl State {
    pub fn new<D>(display: &DisplayHandle) -> Self
    where
        D: GlobalDispatch<ExtWorkspaceManagerV1, ()> + 'static,
    {
        Self {
            _global: display.create_global::<D, ExtWorkspaceManagerV1, _>(VERSION, ()),
            next_binding: 1,
            bindings: Vec::new(),
        }
    }

    /// True when no client is listening, so the session can skip snapshot work.
    pub fn is_idle(&self) -> bool {
        self.bindings.is_empty()
    }

    fn next_binding_id(&mut self) -> u64 {
        let id = self.next_binding;
        self.next_binding += 1;
        id
    }

    /// Registers a new manager binding and advertises the current snapshot.
    ///
    /// `sync` also runs at the event-loop boundary, but advertising here keeps a
    /// client that round-trips immediately after binding from observing an
    /// empty compositor.
    pub fn bind<D>(
        &mut self,
        display: &DisplayHandle,
        client: &Client,
        manager: ExtWorkspaceManagerV1,
        snapshot: &Snapshot,
    ) where
        D: Dispatch<ExtWorkspaceGroupHandleV1, GroupData>
            + Dispatch<ExtWorkspaceHandleV1, WorkspaceData>
            + 'static,
    {
        let id = self.next_binding_id();
        let mut binding = Binding {
            id,
            client: client.clone(),
            manager,
            groups: Vec::new(),
            workspaces: Vec::new(),
            pending: Vec::new(),
        };
        sync_binding::<D>(display, &mut binding, snapshot);
        self.bindings.push(binding);
    }

    /// Pushes the snapshot to every live binding.
    ///
    /// Returns whether any event was sent. An unchanged snapshot sends nothing,
    /// so this is safe to call unconditionally at the event-loop boundary.
    pub fn sync<D>(&mut self, display: &DisplayHandle, snapshot: &Snapshot) -> bool
    where
        D: Dispatch<ExtWorkspaceGroupHandleV1, GroupData>
            + Dispatch<ExtWorkspaceHandleV1, WorkspaceData>
            + 'static,
    {
        if self.bindings.is_empty() {
            return false;
        }
        let mut sent = false;
        for binding in &mut self.bindings {
            sent |= sync_binding::<D>(display, binding, snapshot);
        }
        sent
    }

    /// Associates a late `wl_output` bind with the groups of the same client.
    pub fn output_bound(&mut self, client: &Client, output: &Output, wl_output: &WlOutput) {
        let object = wl_output.id();
        for binding in &mut self.bindings {
            if binding.client.id() != client.id() {
                continue;
            }
            let mut touched = false;
            for group in &mut binding.groups {
                if group.detached || group.output != *output || group.outputs.contains_key(&object)
                {
                    continue;
                }
                group.handle.output_enter(wl_output);
                group.outputs.insert(object.clone(), wl_output.clone());
                touched = true;
            }
            if touched {
                binding.manager.done();
            }
        }
    }

    /// Queues one supported request. Nothing changes before `commit`.
    pub fn queue(&mut self, binding: u64, request: PendingRequest) {
        if let Some(binding) = self.binding_mut(binding) {
            binding.pending.push(request);
        }
    }

    /// Reduces and clears the queued transaction for one binding.
    ///
    /// Returns `None` when the binding is gone or nothing applicable was queued.
    pub fn commit(
        &mut self,
        binding: u64,
        owner_of: impl Fn(ClusterId) -> Option<String>,
        active_on: impl Fn(&str) -> Option<ClusterId>,
    ) -> Option<TransactionPlan> {
        let binding = self.binding_mut(binding)?;
        let requests = std::mem::take(&mut binding.pending);
        if requests.is_empty() {
            return None;
        }
        // A request is applied only while its cluster is still advertised to
        // this binding *through the object the request arrived on*. A destroyed
        // or superseded handle is therefore discarded instead of acted on.
        let advertised = binding
            .workspaces
            .iter()
            .filter(|workspace| !workspace.detached)
            .map(|workspace| (workspace.cluster, Resource::id(&workspace.handle)))
            .collect::<Vec<_>>();
        let live_clusters = advertised
            .iter()
            .map(|(cluster, _)| *cluster)
            .collect::<Vec<_>>();
        // The owner must still have a mapped output advertised to this binding,
        // so a cluster whose output vanished cannot be switched through a stale
        // handle. A group the client destroyed still counts as mapped: only the
        // group object was declined, not the output.
        let groups = binding
            .groups
            .iter()
            .map(|group| group.output.name())
            .collect::<Vec<_>>();
        let owned = |cluster: ClusterId| {
            let output = owner_of(cluster)?;
            groups.contains(&output).then_some(output)
        };

        let applicable = requests
            .iter()
            .filter(|request| advertised.contains(&(request.cluster, request.object.clone())))
            .map(|request| (request.cluster, request.action))
            .collect::<Vec<_>>();
        let plan = reduce_transaction(
            &applicable,
            |cluster| live_clusters.contains(&cluster),
            owned,
            active_on,
        );
        (!plan.is_empty() || plan.focus.is_some()).then_some(plan)
    }

    /// Handles `ext_workspace_manager_v1.stop`: discard pending work and finish
    /// the binding.
    pub fn manager_stopped(&mut self, binding_id: u64) {
        if let Some(binding) = self.binding_mut(binding_id) {
            binding.pending.clear();
            binding.manager.finished();
        }
        self.remove_binding(binding_id);
    }

    /// Drops one manager binding.
    ///
    /// Called for `stop` and for the manager object's `destroyed` callback,
    /// which wayland-server also runs for every object of a disconnecting
    /// client. The cluster records themselves are never touched.
    pub fn remove_binding(&mut self, binding_id: u64) {
        self.bindings.retain(|binding| binding.id != binding_id);
    }

    /// Handles destruction of a group handle: stop sending events to it without
    /// forgetting which workspaces belong to it.
    pub fn group_destroyed(&mut self, binding: u64, handle: &ExtWorkspaceGroupHandleV1) {
        let Some(binding) = self.binding_mut(binding) else {
            return;
        };
        let object = handle.id();
        if let Some(group) = binding
            .groups
            .iter_mut()
            .find(|group| Resource::id(&group.handle) == object)
        {
            group.detached = true;
            group.outputs.clear();
        }
    }

    /// Handles destruction of a workspace handle: retire the cluster from this
    /// binding without touching Halley's cluster record.
    pub fn workspace_destroyed(&mut self, binding: u64, handle: &ExtWorkspaceHandleV1) {
        let Some(binding) = self.binding_mut(binding) else {
            return;
        };
        let object = Resource::id(handle);
        let Some(workspace) = binding
            .workspaces
            .iter_mut()
            .find(|workspace| Resource::id(&workspace.handle) == object)
        else {
            return;
        };
        workspace.detached = true;
        let cluster = workspace.cluster;
        for group in &mut binding.groups {
            group.workspaces.retain(|candidate| *candidate != cluster);
        }
        binding.pending.retain(|request| request.object != object);
    }

    /// Resolves a manager resource back to its binding.
    pub fn binding_of(&self, client: &ClientId, manager: &ExtWorkspaceManagerV1) -> Option<u64> {
        let object = manager.id();
        self.bindings
            .iter()
            .find(|binding| {
                binding.client.id() == *client && Resource::id(&binding.manager) == object
            })
            .map(|binding| binding.id)
    }

    fn binding_mut(&mut self, id: u64) -> Option<&mut Binding> {
        self.bindings.iter_mut().find(|binding| binding.id == id)
    }
}

// ---------------------------------------------------------------------------
// Snapshot synchronisation
// ---------------------------------------------------------------------------

/// Reconciles one binding against the snapshot and emits only what changed.
/// Returns whether anything was sent.
fn sync_binding<D>(display: &DisplayHandle, binding: &mut Binding, snapshot: &Snapshot) -> bool
where
    D: Dispatch<ExtWorkspaceGroupHandleV1, GroupData>
        + Dispatch<ExtWorkspaceHandleV1, WorkspaceData>
        + 'static,
{
    let Binding {
        id,
        client,
        manager,
        groups,
        workspaces,
        pending,
    } = binding;
    let mut touched = false;

    // 1. Retire groups whose output is gone, or whose output was replaced by a
    //    new incarnation under the same name. Membership removal is emitted
    //    before the group is removed, as the protocol requires.
    let mut index = 0;
    while index < groups.len() {
        let stale = !snapshot
            .groups
            .iter()
            .any(|candidate| candidate.output == groups[index].output);
        if !stale {
            index += 1;
            continue;
        }
        let mut group = groups.remove(index);
        if !group.detached {
            for cluster in group.workspaces.iter() {
                if let Some(workspace) = workspaces
                    .iter()
                    .find(|workspace| workspace.cluster == *cluster && !workspace.detached)
                {
                    group.handle.workspace_leave(&workspace.handle);
                }
            }
            for output in group.outputs.values().filter(|output| output.is_alive()) {
                group.handle.output_leave(output);
            }
            group.handle.removed();
        }
        for cluster in group.workspaces.iter() {
            if let Some(workspace) = workspaces
                .iter_mut()
                .find(|workspace| workspace.cluster == *cluster)
            {
                workspace.group = None;
            }
        }
        group.outputs.clear();
        touched = true;
    }

    // 2. Retire workspaces orphaned by stale groups before synchronising any
    //    replacement groups. Pending requests are tied to the retired object,
    //    and a replacement output incarnation always gets fresh handles.
    let mut index = 0;
    while index < workspaces.len() {
        if workspaces[index].group.is_some() {
            index += 1;
            continue;
        }
        let workspace = workspaces.remove(index);
        let object = Resource::id(&workspace.handle);
        pending.retain(|request| request.object != object);
        if !workspace.detached {
            workspace.handle.removed();
        }
        touched = true;
    }

    // 3. Advertise and update the groups that should exist.
    for snapshot_group in &snapshot.groups {
        index = match groups
            .iter()
            .position(|group| group.output == snapshot_group.output)
        {
            Some(index) => index,
            None => {
                let Ok(handle) = client.create_resource::<ExtWorkspaceGroupHandleV1, _, D>(
                    display,
                    VERSION,
                    GroupData { binding: *id },
                ) else {
                    continue;
                };
                manager.workspace_group(&handle);
                handle.capabilities(GROUP_CAPABILITIES);
                groups.push(GroupBinding {
                    output: snapshot_group.output.clone(),
                    handle,
                    detached: false,
                    outputs: HashMap::new(),
                    workspaces: Vec::new(),
                });
                touched = true;
                groups.len() - 1
            }
        };

        touched |= sync_group::<D>(
            display,
            client,
            *id,
            groups,
            index,
            workspaces,
            manager,
            snapshot_group,
        );
    }

    // 4. Retire workspaces their output no longer advertises. The client-side
    //    handles become inert; a later re-advertisement uses a fresh object.
    let mut index = 0;
    while index < workspaces.len() {
        let retire = workspaces[index].group.is_none() && !workspaces[index].detached;
        if !retire {
            index += 1;
            continue;
        }
        workspaces.remove(index).handle.removed();
        touched = true;
    }

    if touched {
        manager.done();
    }
    touched
}

#[allow(clippy::too_many_arguments)]
fn sync_group<D>(
    display: &DisplayHandle,
    client: &Client,
    binding: u64,
    groups: &mut Vec<GroupBinding>,
    index: usize,
    workspaces: &mut Vec<WorkspaceBinding>,
    manager: &ExtWorkspaceManagerV1,
    snapshot: &GroupSnapshot,
) -> bool
where
    D: Dispatch<ExtWorkspaceGroupHandleV1, GroupData>
        + Dispatch<ExtWorkspaceHandleV1, WorkspaceData>
        + 'static,
{
    let mut touched = false;
    let detached = groups[index].detached;

    // `wl_output` association. `output_bound` covers the common case, but a
    // client that binds wl_output before the manager, or binds it twice, is
    // reconciled here.
    if !detached {
        groups[index].outputs.retain(|_, output| output.is_alive());
        let bound = snapshot
            .output
            .client_outputs(client)
            .map(|output| (output.id(), output))
            .collect::<Vec<_>>();
        for (object, output) in bound {
            if groups[index].outputs.contains_key(&object) {
                continue;
            }
            groups[index].handle.output_enter(&output);
            groups[index].outputs.insert(object, output);
            touched = true;
        }
    }

    // Members this group no longer advertises leave the group before anything
    // else references them.
    let stale = groups[index]
        .workspaces
        .iter()
        .copied()
        .filter(|cluster| !snapshot.workspaces.iter().any(|entry| entry.id == *cluster))
        .collect::<Vec<_>>();
    for cluster in stale {
        if let Some(workspace) = workspaces
            .iter()
            .find(|workspace| workspace.cluster == cluster && !workspace.detached)
        {
            if !detached {
                groups[index].handle.workspace_leave(&workspace.handle);
            }
            touched = true;
        }
        if let Some(workspace) = workspaces
            .iter_mut()
            .find(|workspace| workspace.cluster == cluster)
        {
            workspace.group = None;
        }
        groups[index]
            .workspaces
            .retain(|candidate| *candidate != cluster);
    }

    for entry in &snapshot.workspaces {
        let existing = workspaces
            .iter()
            .position(|workspace| workspace.cluster == entry.id);
        let Some(position) = existing else {
            let Ok(handle) = client.create_resource::<ExtWorkspaceHandleV1, _, D>(
                display,
                VERSION,
                WorkspaceData {
                    binding,
                    cluster: entry.id,
                },
            ) else {
                continue;
            };
            manager.workspace(&handle);
            handle.capabilities(WORKSPACE_CAPABILITIES);
            handle.name(entry.name.clone());
            handle.coordinates(coordinates(entry.order));
            handle.state(state_of(entry.active));
            if !detached {
                groups[index].handle.workspace_enter(&handle);
            }
            groups[index].workspaces.push(entry.id);
            workspaces.push(WorkspaceBinding {
                cluster: entry.id,
                handle,
                group: Some(snapshot.output.clone()),
                name: entry.name.clone(),
                order: entry.order,
                active: entry.active,
                detached: false,
            });
            touched = true;
            continue;
        };

        if workspaces[position].detached {
            // The client destroyed this object; do not recreate it.
            continue;
        }

        // A cluster that moved between outputs changes group before its
        // properties are refreshed, so a client never sees it in two groups.
        if workspaces[position].group.as_ref() != Some(&snapshot.output) {
            let previous = workspaces[position].group.clone();
            if let Some(previous) = previous
                && let Some(old) = groups
                    .iter_mut()
                    .find(|group| group.output == previous && !group.detached)
            {
                old.handle.workspace_leave(&workspaces[position].handle);
                old.workspaces.retain(|candidate| *candidate != entry.id);
            }
            workspaces[position].group = Some(snapshot.output.clone());
            if !detached {
                groups[index]
                    .handle
                    .workspace_enter(&workspaces[position].handle);
            }
            touched = true;
        }

        let handle = workspaces[position].handle.clone();
        if workspaces[position].name != entry.name {
            workspaces[position].name = entry.name.clone();
            handle.name(entry.name.clone());
            touched = true;
        }
        if workspaces[position].order != entry.order {
            workspaces[position].order = entry.order;
            handle.coordinates(coordinates(entry.order));
            touched = true;
        }
        if workspaces[position].active != entry.active {
            workspaces[position].active = entry.active;
            handle.state(state_of(entry.active));
            touched = true;
        }
        if !groups[index].workspaces.contains(&entry.id) {
            groups[index].workspaces.push(entry.id);
        }
    }

    touched
}

// ---------------------------------------------------------------------------
// Dispatch plumbing
// ---------------------------------------------------------------------------

/// Builds a fresh manager object for a client that bound the global.
///
/// The caller supplies the current snapshot so the client does not observe an
/// empty compositor before the next event-loop synchronisation.
pub fn init_manager<D>(
    state: &mut State,
    display: &DisplayHandle,
    client: &Client,
    resource: New<ExtWorkspaceManagerV1>,
    data_init: &mut DataInit<'_, D>,
    snapshot: &Snapshot,
) -> ExtWorkspaceManagerV1
where
    D: Dispatch<ExtWorkspaceManagerV1, ()>
        + Dispatch<ExtWorkspaceGroupHandleV1, GroupData>
        + Dispatch<ExtWorkspaceHandleV1, WorkspaceData>
        + 'static,
{
    let manager = data_init.init(resource, ());
    state.bind::<D>(display, client, manager.clone(), snapshot);
    manager
}

/// Handles one `ext_workspace_manager_v1` request.
pub fn manager_request(
    state: &mut State,
    binding: u64,
    request: ext_workspace_manager_v1::Request,
    owner_of: impl Fn(ClusterId) -> Option<String>,
    active_on: impl Fn(&str) -> Option<ClusterId>,
) -> Option<TransactionPlan> {
    match request {
        ext_workspace_manager_v1::Request::Commit => state.commit(binding, owner_of, active_on),
        ext_workspace_manager_v1::Request::Stop => {
            state.manager_stopped(binding);
            None
        }
        // `Request` is non-exhaustive so a future protocol revision cannot break
        // the build; unknown requests change nothing.
        _ => None,
    }
}

/// Handles one `ext_workspace_group_handle_v1` request.
///
/// `create_workspace` is never enabled by `GROUP_CAPABILITIES`, so it is
/// ignored here exactly as the protocol requires.
pub fn group_request(
    state: &mut State,
    binding: u64,
    handle: &ExtWorkspaceGroupHandleV1,
    request: ext_workspace_group_handle_v1::Request,
) {
    if matches!(request, ext_workspace_group_handle_v1::Request::Destroy) {
        state.group_destroyed(binding, handle);
    }
}

/// Handles one `ext_workspace_handle_v1` request.
///
/// Only `activate` and `deactivate` are advertised; `remove` and `assign` are
/// ignored without mutating Halley.
pub fn workspace_request(
    state: &mut State,
    binding: u64,
    handle: &ExtWorkspaceHandleV1,
    cluster: ClusterId,
    request: ext_workspace_handle_v1::Request,
) {
    let action = match request {
        ext_workspace_handle_v1::Request::Activate => PendingAction::Activate,
        ext_workspace_handle_v1::Request::Deactivate => PendingAction::Deactivate,
        ext_workspace_handle_v1::Request::Destroy => {
            state.workspace_destroyed(binding, handle);
            return;
        }
        // `remove` and `assign` are never advertised, and `Request` is
        // non-exhaustive: unsupported requests are ignored without mutating
        // Halley.
        _ => return,
    };
    state.queue(
        binding,
        PendingRequest {
            cluster,
            action,
            // Note: `Resource::id`, not the protocol's `id` event sender.
            object: Resource::id(handle),
        },
    );
}

#[cfg(test)]
mod tests {
    use super::*;

    fn cluster(raw: u64) -> ClusterId {
        ClusterId::new(raw)
    }

    fn owners(pairs: &[(u64, &str)]) -> Vec<(ClusterId, String)> {
        pairs
            .iter()
            .map(|(id, output)| (cluster(*id), (*output).to_string()))
            .collect()
    }

    fn reduce(
        requests: &[(ClusterId, PendingAction)],
        owners: &[(ClusterId, String)],
        active: &[(String, Option<ClusterId>)],
    ) -> TransactionPlan {
        reduce_transaction(
            requests,
            |_| true,
            |id| {
                owners
                    .iter()
                    .find(|(candidate, _)| *candidate == id)
                    .map(|(_, output)| output.clone())
            },
            |output| {
                active
                    .iter()
                    .find(|(candidate, _)| candidate == output)
                    .and_then(|(_, selection)| *selection)
            },
        )
    }

    #[test]
    fn repeated_activation_collapses_to_one_selection() {
        let owners = owners(&[(1, "DP-1")]);
        let active = vec![("DP-1".to_string(), None)];

        let plan = reduce(
            &[
                (cluster(1), PendingAction::Activate),
                (cluster(1), PendingAction::Activate),
            ],
            &owners,
            &active,
        );

        assert_eq!(
            plan.selections,
            vec![("DP-1".to_string(), Some(cluster(1)))]
        );
        assert_eq!(plan.focus, Some(("DP-1".to_string(), cluster(1))));
    }

    #[test]
    fn activating_the_already_active_workspace_is_a_no_op() {
        let owners = owners(&[(1, "DP-1")]);
        let active = vec![("DP-1".to_string(), Some(cluster(1)))];

        let plan = reduce(&[(cluster(1), PendingAction::Activate)], &owners, &active);

        assert!(plan.is_empty());
        assert_eq!(plan.focus, None);
    }

    #[test]
    fn final_activation_per_output_wins() {
        let owners = owners(&[(1, "DP-1"), (2, "DP-1")]);
        let active = vec![("DP-1".to_string(), None)];

        let plan = reduce(
            &[
                (cluster(1), PendingAction::Activate),
                (cluster(2), PendingAction::Activate),
            ],
            &owners,
            &active,
        );

        assert_eq!(
            plan.selections,
            vec![("DP-1".to_string(), Some(cluster(2)))]
        );
        assert_eq!(plan.focus, Some(("DP-1".to_string(), cluster(2))));
    }

    #[test]
    fn deactivating_an_unrelated_workspace_leaves_the_selection_alone() {
        let owners = owners(&[(1, "DP-1"), (2, "DP-1")]);
        let active = vec![("DP-1".to_string(), Some(cluster(1)))];

        let plan = reduce(&[(cluster(2), PendingAction::Deactivate)], &owners, &active);

        assert!(plan.is_empty());
        assert_eq!(plan.focus, None);
    }

    #[test]
    fn deactivating_the_active_workspace_clears_the_output() {
        let owners = owners(&[(1, "DP-1")]);
        let active = vec![("DP-1".to_string(), Some(cluster(1)))];

        let plan = reduce(&[(cluster(1), PendingAction::Deactivate)], &owners, &active);

        assert_eq!(plan.selections, vec![("DP-1".to_string(), None)]);
        assert_eq!(plan.focus, None);
    }

    #[test]
    fn deactivating_field_mode_is_a_no_op() {
        let owners = owners(&[(1, "DP-1")]);
        let active = vec![("DP-1".to_string(), None)];

        let plan = reduce(&[(cluster(1), PendingAction::Deactivate)], &owners, &active);

        assert!(plan.is_empty());
    }

    #[test]
    fn deactivation_after_activation_clears_the_same_output() {
        let owners = owners(&[(1, "DP-1")]);
        let active = vec![("DP-1".to_string(), None)];

        let plan = reduce(
            &[
                (cluster(1), PendingAction::Activate),
                (cluster(1), PendingAction::Deactivate),
            ],
            &owners,
            &active,
        );

        assert!(plan.is_empty(), "the transaction nets out to no change");
    }

    #[test]
    fn a_multi_output_transaction_switches_every_output_but_focuses_one() {
        let owners = owners(&[(1, "DP-1"), (2, "DP-2"), (3, "DP-1")]);
        let active = vec![
            ("DP-1".to_string(), Some(cluster(1))),
            ("DP-2".to_string(), None),
        ];

        let plan = reduce(
            &[
                (cluster(2), PendingAction::Activate),
                (cluster(3), PendingAction::Activate),
            ],
            &owners,
            &active,
        );

        assert_eq!(
            plan.selections,
            vec![
                ("DP-2".to_string(), Some(cluster(2))),
                ("DP-1".to_string(), Some(cluster(3))),
            ],
            "both changed outputs are switched"
        );
        assert_eq!(
            plan.focus,
            Some(("DP-1".to_string(), cluster(3))),
            "only the final applicable activation takes the keyboard"
        );
    }

    #[test]
    fn dead_targets_are_discarded() {
        let owners = owners(&[(1, "DP-1")]);
        let active = vec![("DP-1".to_string(), None)];

        let plan = reduce_transaction(
            &[
                (cluster(1), PendingAction::Activate),
                (cluster(9), PendingAction::Activate),
            ],
            |id| id != cluster(1),
            |id| {
                owners
                    .iter()
                    .find(|(candidate, _)| *candidate == id)
                    .map(|(_, output)| output.clone())
            },
            |output| {
                active
                    .iter()
                    .find(|(candidate, _)| candidate == output)
                    .and_then(|(_, selection)| *selection)
            },
        );

        assert!(plan.is_empty(), "a destroyed target must not be applied");
        assert_eq!(plan.focus, None);
    }

    #[test]
    fn coordinates_are_a_single_dense_zero_based_dimension() {
        assert_eq!(coordinates(1), 0u32.to_ne_bytes().to_vec());
        assert_eq!(coordinates(3), 2u32.to_ne_bytes().to_vec());
    }

    #[test]
    fn only_active_workspaces_carry_a_state_bit() {
        assert_eq!(
            state_of(true).bits(),
            ext_workspace_handle_v1::State::Active.bits()
        );
        assert_eq!(state_of(false).bits(), 0);
    }

    #[test]
    fn advertised_capabilities_are_activate_and_deactivate_only() {
        assert_eq!(GROUP_CAPABILITIES.bits(), 0);
        assert_eq!(
            WORKSPACE_CAPABILITIES.bits(),
            ext_workspace_handle_v1::WorkspaceCapabilities::Activate.bits()
                | ext_workspace_handle_v1::WorkspaceCapabilities::Deactivate.bits()
        );
        assert!(
            !WORKSPACE_CAPABILITIES
                .contains(ext_workspace_handle_v1::WorkspaceCapabilities::Remove)
        );
        assert!(
            !WORKSPACE_CAPABILITIES
                .contains(ext_workspace_handle_v1::WorkspaceCapabilities::Assign)
        );
    }
}
